//! Persistence layer (0.10.0).
//!
//! One `sqlx::AnyPool` serves both PostgreSQL (primary, via `DATABASE_URL`)
//! and embedded SQLite (fallback). All SQL lives behind this module; the
//! dialect rules of `design/persistence.md` §3.1 apply everywhere:
//!
//! - placeholders are always written `?` in the SQL text (the only spelling
//!   SQLite accepts); the Any driver passes statements to PG verbatim — it
//!   does NOT translate `?` (sqlx 0.8.6, verified in `sqlx-core/src/any/`
//!   and by 0.10.0 E2E on real PG) — so the store layer rewrites `?` to
//!   `$1..$n` itself before execution ([`SqlxStore::sql`] /
//!   [`placeholders::rewrite`]);
//! - no `RETURNING` (primary keys are Rust-side UUIDs);
//! - JSON columns are `TEXT`, serialized/deserialized by the store layer;
//! - timestamps are generated by chrono on the Rust side, never by DDL
//!   defaults. NOTE (finding from verification point A/D): the `Any` driver
//!   has no `Type<Any>` impls for chrono types — only bool/int/float/str/blob
//!   are supported — and SQLite refuses `String` decode from a column
//!   declared `TIMESTAMP`. Timestamp columns are therefore declared `TEXT`
//!   and carry fixed-width RFC 3339 UTC strings
//!   (`2026-09-03T10:00:00.000000Z`), encoded/decoded by the store layer.
//!   Fixed-width UTC `Z` formatting keeps lexicographic order ==
//!   chronological order, which `ORDER BY created_at` pagination relies on.
//!
//! Shipped so far: connection/migration skeleton, verification-point-A/D
//! smoke tests, and the configuration domain ([`traits::ConfigStore`]
//! implemented on [`SqlxStore`] in [`sqlx`], row codecs + the `enc:`
//! boundary in [`rows`]). `ReviewStore` / `DiscussionStore` land in later
//! steps.

pub mod llm_samples;
pub mod placeholders;
pub mod rows;
pub mod sqlx;
pub mod traits;

use std::borrow::Cow;
use std::path::Path;

use anyhow::{Context, Result};
use chrono::{DateTime, SecondsFormat, Utc};

/// Embedded migrations (compiled in via `sqlx::migrate!`).
static MIGRATOR: ::sqlx::migrate::Migrator = ::sqlx::migrate!("./migrations");

/// Which storage backend a [`SqlxStore`] pool talks to, recorded at connect
/// time from the URL (design/persistence.md §4.3). Surfaced read-only via
/// `GET /api/v1/system/health` as `storage_backend`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendKind {
    /// `postgres://` / `postgresql://` URL.
    Postgresql,
    /// Everything else (embedded SQLite, incl. in-memory).
    Sqlite,
}

impl BackendKind {
    /// Wire value exposed to the API layer (`"postgresql"` / `"sqlite"`).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Postgresql => "postgresql",
            Self::Sqlite => "sqlite",
        }
    }
}

/// URL discrimination per design/persistence.md §4.3: `postgres://` /
/// `postgresql://` → PostgreSQL; anything else → SQLite.
fn backend_kind_of(url: &str) -> BackendKind {
    if url.starts_with("postgres://") || url.starts_with("postgresql://") {
        BackendKind::Postgresql
    } else {
        BackendKind::Sqlite
    }
}

/// SQLx store backed by an `Any` pool (PostgreSQL or SQLite).
///
/// Besides pool construction / SQLite pragmas / migrations, the store holds
/// the at-rest encryption key (`secrets.key`, per config dir): the `enc:`
/// boundary lives in [`rows`], and PG deployments still read the key from
/// the server-local config dir (design/persistence.md §6.2).
#[derive(Debug, Clone)]
pub struct SqlxStore {
    pool: ::sqlx::AnyPool,
    kind: BackendKind,
    /// `sqlite::memory:` (tests, embedded use): there is no file behind the
    /// pool, so nothing on disk can be checked (RENG-106's storage probe asks).
    in_memory: bool,
    pub(crate) key: [u8; 32],
}

impl SqlxStore {
    /// Connect to the database identified by `url`.
    ///
    /// URL discrimination (design/persistence.md §4.3):
    /// - `postgres://` / `postgresql://` → PostgreSQL;
    /// - anything else → SQLite.
    ///
    /// For SQLite, after the pool is built the connection pragmas required by
    /// the schema are applied: WAL journal, foreign keys on, 5 s busy timeout.
    /// The secrets key resolves via the standard config-dir resolution
    /// (`persist::resolve_ui_state_path` → `key_path_for`).
    pub async fn connect(url: &str) -> Result<Self> {
        let state_path = crate::server::api::config::persist::resolve_ui_state_path()
            .context("cannot resolve the config dir for the secrets key")?;
        let key = crate::config::secrets::load_or_create_key(&crate::config::secrets::key_path_for(&state_path))?;
        Self::connect_with_key(url, key).await
    }

    /// Connect with an explicit secrets key (used by [`Self::connect`] and
    /// available to tests that need a stable key without a config dir).
    pub async fn connect_with_key(url: &str, key: [u8; 32]) -> Result<Self> {
        ::sqlx::any::install_default_drivers();
        let kind = backend_kind_of(url);
        let pool = ::sqlx::any::AnyPoolOptions::new().connect(url).await.with_context(|| {
            format!(
                "failed to connect to database ({url_scheme})",
                url_scheme = scheme_of(url)
            )
        })?;
        if kind == BackendKind::Sqlite {
            apply_sqlite_pragmas(&pool).await?;
        }
        Ok(Self {
            pool,
            kind,
            in_memory: url.contains(":memory:"),
            key,
        })
    }

    /// Connect to the default embedded SQLite database under `config_dir`
    /// (`sqlite://{config_dir}/review.db?mode=rwc`, created on demand); the
    /// secrets key is `{config_dir}/secrets.key`, created on first use.
    pub async fn connect_default(config_dir: &Path) -> Result<Self> {
        std::fs::create_dir_all(config_dir)
            .with_context(|| format!("failed to create config dir {}", config_dir.display()))?;
        let key = crate::config::secrets::load_or_create_key(
            &config_dir.join(crate::config::secrets::SECRETS_KEY_FILE_NAME),
        )?;
        let url = format!("sqlite://{}/review.db?mode=rwc", config_dir.display());
        Self::connect_with_key(&url, key).await
    }

    /// In-memory SQLite store for unit tests.
    ///
    /// `max_connections(1)` is mandatory: with a larger pool each connection
    /// would be an independent in-memory database. Uses an ephemeral random
    /// key — enough for round-trip tests, but nothing persists between
    /// instances.
    pub async fn new_in_memory() -> Result<Self> {
        let mut key = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut key);
        ::sqlx::any::install_default_drivers();
        let pool = ::sqlx::any::AnyPoolOptions::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .context("failed to open in-memory sqlite database")?;
        apply_sqlite_pragmas(&pool).await?;
        Ok(Self {
            pool,
            kind: BackendKind::Sqlite,
            in_memory: true,
            key,
        })
    }

    /// Apply the embedded migrations (idempotent — already-applied
    /// migrations are skipped based on the `_sqlx_migrations` ledger).
    pub async fn migrate(&self) -> Result<()> {
        MIGRATOR.run(&self.pool).await.context("database migration failed")?;
        Ok(())
    }

    /// The storage backend this pool talks to, recorded at connect time
    /// (PostgreSQL or SQLite).
    pub fn backend_kind(&self) -> BackendKind {
        self.kind
    }

    /// True for `sqlite::memory:` — no file behind the pool, so a
    /// file-permission diagnosis has nothing to inspect (RENG-106).
    pub fn is_in_memory(&self) -> bool {
        self.in_memory
    }

    /// Access the underlying pool (used by trait implementations in
    /// [`sqlx`] and by tests).
    pub fn pool(&self) -> &::sqlx::AnyPool {
        &self.pool
    }

    /// Adapt a statement's `?` placeholders for this store's backend —
    /// see [`adapt_sql`]. Every statement executed through this store must
    /// pass through here (design/persistence.md §3.1 placeholder row).
    pub(crate) fn sql<'a>(&self, sql: &'a str) -> Cow<'a, str> {
        adapt_sql(self.kind, sql)
    }
}

/// Adapt a statement for `kind`: PostgreSQL gets `?` rewritten to `$1..$n`
/// (the Any driver passes SQL through verbatim — see [`placeholders`]),
/// SQLite gets the text unchanged. Borrows whenever no rewrite is needed.
///
/// This is a pure text transform over the SQL *statement*; bind values are
/// attached afterwards and are never seen by the rewriter.
pub(crate) fn adapt_sql(kind: BackendKind, sql: &str) -> Cow<'_, str> {
    match kind {
        BackendKind::Postgresql if sql.contains('?') => Cow::Owned(placeholders::rewrite(sql)),
        _ => Cow::Borrowed(sql),
    }
}

/// Scheme prefix of a database URL, for error messages that must not leak
/// credentials embedded in the URL.
fn scheme_of(url: &str) -> &str {
    url.split("://").next().unwrap_or(url)
}

async fn apply_sqlite_pragmas(pool: &::sqlx::AnyPool) -> Result<()> {
    // Executed as separate statements: Any queries are single-statement.
    for pragma in [
        "PRAGMA journal_mode=WAL;",
        "PRAGMA foreign_keys=ON;",
        "PRAGMA busy_timeout=5000;",
    ] {
        ::sqlx::query(pragma)
            .execute(pool)
            .await
            .with_context(|| format!("failed to apply {pragma}"))?;
    }
    Ok(())
}

/// Encode a timestamp for a `TEXT` timestamp column. The Any driver has no
/// chrono `Type` impls, so values cross as fixed-width RFC 3339 UTC strings
/// (`2026-09-03T10:00:00.000000Z`); lexicographic order == chronological
/// order, which `ORDER BY created_at` pagination relies on.
pub(crate) fn encode_ts(ts: &DateTime<Utc>) -> String {
    ts.to_rfc3339_opts(SecondsFormat::Micros, true)
}

/// Decode a timestamp produced by [`encode_ts`]. Used by the review-domain
/// codecs ([`rows`]) and by tests.
pub(crate) fn decode_ts(s: &str) -> Result<DateTime<Utc>> {
    Ok(DateTime::parse_from_rfc3339(s)
        .with_context(|| format!("invalid RFC 3339 timestamp in database: {s:?}"))?
        .with_timezone(&Utc))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ::sqlx::Row;
    use chrono::TimeZone;

    use crate::server::task_queue::TaskEntry;
    use uuid::Uuid;

    /// URL discrimination per §4.3: `postgres://` / `postgresql://` →
    /// PostgreSQL, everything else → SQLite. Pure-function-level coverage of
    /// the `"postgresql"` wire value (a live PG is not available in unit
    /// tests; the end-to-end PG smoke test is `migrate_on_postgres_smoke`).
    #[test]
    fn backend_kind_discriminates_by_url_scheme() {
        assert_eq!(
            backend_kind_of("postgres://u:p@db.example/review"),
            BackendKind::Postgresql
        );
        assert_eq!(
            backend_kind_of("postgresql://u:p@db.example/review"),
            BackendKind::Postgresql
        );
        assert_eq!(BackendKind::Postgresql.as_str(), "postgresql");

        assert_eq!(backend_kind_of("sqlite:///tmp/review.db?mode=rwc"), BackendKind::Sqlite);
        assert_eq!(backend_kind_of("sqlite::memory:"), BackendKind::Sqlite);
        assert_eq!(BackendKind::Sqlite.as_str(), "sqlite");
    }

    /// `adapt_sql` dispatch: PG rewrites `?` (and borrows when there is
    /// nothing to rewrite), SQLite always borrows the original text.
    #[test]
    fn adapt_sql_rewrites_for_postgres_only() {
        assert_eq!(
            adapt_sql(BackendKind::Postgresql, "SELECT * FROM t WHERE a = ? AND b = ?"),
            "SELECT * FROM t WHERE a = $1 AND b = $2"
        );
        assert!(
            matches!(
                adapt_sql(BackendKind::Postgresql, "SELECT * FROM t WHERE a = ?"),
                Cow::Owned(_)
            ),
            "PG with placeholders must own the rewritten text"
        );
        assert!(
            matches!(adapt_sql(BackendKind::Postgresql, "SELECT * FROM t"), Cow::Borrowed(_)),
            "PG without placeholders must borrow"
        );
        assert!(
            matches!(
                adapt_sql(BackendKind::Sqlite, "SELECT * FROM t WHERE a = ?"),
                Cow::Borrowed(_)
            ),
            "SQLite must get the original `?` text untouched"
        );
    }

    /// An in-memory SQLite store reports the sqlite backend kind.
    #[tokio::test]
    async fn in_memory_store_reports_sqlite_backend_kind() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        assert_eq!(store.backend_kind(), BackendKind::Sqlite);
        assert_eq!(store.backend_kind().as_str(), "sqlite");
    }

    /// 验证点 A(a): in-memory SQLite + migrate creates the schema, and a
    /// second migrate run is an idempotent no-op.
    #[tokio::test]
    async fn migrate_creates_schema_and_is_idempotent() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let tables: Vec<String> = ::sqlx::query(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
        )
        .fetch_all(store.pool())
        .await
        .unwrap()
        .into_iter()
        .map(|row| row.get::<String, _>(0))
        .collect();
        for expected in [
            "app_settings",
            "expert_reports",
            "git_platforms",
            "llm_call_samples",
            "llm_probe_samples",
            "llm_providers",
            "mr_discussions",
            "review_contexts",
            "reviews",
        ] {
            assert!(
                tables.iter().any(|t| t == expected),
                "missing table {expected}, got {tables:?}"
            );
        }

        // Second run: must succeed and apply nothing new.
        store.migrate().await.unwrap();
        let applied: i64 = ::sqlx::query_scalar("SELECT COUNT(*) FROM _sqlx_migrations")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(
            applied, 7,
            "0001_init + 0002_llm_snapshot + 0003_participant_meta + 0004_llm_call_samples + 0005_llm_entry_fp \
             + 0006_llm_sample_ttfb + 0007_llm_probe_samples should be recorded"
        );

        // 0002 (RENG-38): the snapshot columns exist on both history tables.
        let er_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('expert_reports')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            er_cols.iter().any(|c| c == "llm_provider"),
            "expert_reports missing llm_provider"
        );
        assert!(
            er_cols.iter().any(|c| c == "llm_model"),
            "expert_reports missing llm_model"
        );
        let rv_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('reviews')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            rv_cols.iter().any(|c| c == "llm_summary"),
            "reviews missing llm_summary"
        );

        // 0003 (RENG-43): the discussion-author columns exist too.
        let d_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('mr_discussions')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        for expected in ["author_id", "author_avatar_url", "author_bot"] {
            assert!(
                d_cols.iter().any(|c| c == expected),
                "mr_discussions missing {expected}, got {d_cols:?}"
            );
        }

        // 0004 (RENG-57): the call-sample table has the columns the recorder
        // and the aggregate read, and its window index.
        let s_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('llm_call_samples')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        for expected in [
            "id",
            "review_id",
            "provider",
            "model",
            "latency_ms",
            "success",
            "error",
            "chain_position",
            "attempt",
            "created_at",
        ] {
            assert!(
                s_cols.iter().any(|c| c == expected),
                "llm_call_samples missing {expected}, got {s_cols:?}"
            );
        }
        let s_idx: Vec<String> = ::sqlx::query_scalar("SELECT name FROM sqlite_master WHERE type='index'")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            s_idx.iter().any(|i| i == "idx_llm_call_samples_window"),
            "the window index is what keeps the aggregate a range scan: {s_idx:?}"
        );
    }

    /// 0005 (RENG-75): the entry-fingerprint column exists and is NULL on rows
    /// that predate it (the aggregate's unmarked bucket), and the migration is
    /// idempotent — running it again keeps both the column and the old rows.
    #[tokio::test]
    async fn migrate_0005_adds_entry_fp_and_preserves_old_rows() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let s_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('llm_call_samples')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            s_cols.iter().any(|c| c == "entry_fp"),
            "llm_call_samples missing entry_fp, got {s_cols:?}"
        );
        // No second window index: the aggregate folds by fp in Rust after the
        // same (created_at, provider) range scan (see 0005's own comment).
        let s_idx: Vec<String> = ::sqlx::query_scalar("SELECT name FROM sqlite_master WHERE type='index'")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            !s_idx.iter().any(|i| i.contains("entry_fp")),
            "no fp index — the window scan is already bounded: {s_idx:?}"
        );

        // A pre-0005-shaped row (no fp) survives with entry_fp NULL, across a
        // repeated migrate.
        ::sqlx::query(
            "INSERT INTO llm_call_samples (id, provider, model, latency_ms, success, attempt, created_at) \
             VALUES ('row-1', 'xiaomi', 'mimo', 120, 1, 1, '2026-09-14T10:00:00.000000Z')",
        )
        .execute(store.pool())
        .await
        .unwrap();
        store.migrate().await.unwrap();
        let (provider, entry_fp): (String, Option<String>) =
            ::sqlx::query_as("SELECT provider, entry_fp FROM llm_call_samples WHERE id = 'row-1'")
                .fetch_one(store.pool())
                .await
                .unwrap();
        assert_eq!(provider, "xiaomi", "the old row is preserved");
        assert_eq!(entry_fp, None, "pre-0005 rows keep entry_fp NULL (the unmarked bucket)");
    }

    /// 0006 (RENG-77 §5): the time-to-first-byte column exists and is NULL on
    /// rows that predate it (a measurement that was never taken — the latency
    /// aggregate excludes those instead of averaging them in as 0), and the
    /// migration is idempotent: a repeated run keeps both the column and the
    /// old rows.
    #[tokio::test]
    async fn migrate_0006_adds_ttfb_and_preserves_old_rows() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let s_cols: Vec<String> = ::sqlx::query_scalar("SELECT name FROM pragma_table_info('llm_call_samples')")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            s_cols.iter().any(|c| c == "ttfb_ms"),
            "llm_call_samples missing ttfb_ms, got {s_cols:?}"
        );
        // No new index: `ttfb_ms` is a projected column, not a filter — the
        // read path is still the (created_at, provider) window scan (0004/0006).
        let s_idx: Vec<String> = ::sqlx::query_scalar("SELECT name FROM sqlite_master WHERE type='index'")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            !s_idx.iter().any(|i| i.contains("ttfb")),
            "no ttfb index — the window scan is already bounded: {s_idx:?}"
        );

        // A pre-0006-shaped row (no ttfb) survives with ttfb_ms NULL across a
        // repeated migrate, and the column is nullable (not defaulted to 0).
        ::sqlx::query(
            "INSERT INTO llm_call_samples (id, provider, model, latency_ms, success, attempt, created_at) \
             VALUES ('row-ttfb', 'deepseek', 'deepseek-v4-flash', 17600, 1, 1, '2026-09-14T10:00:00.000000Z')",
        )
        .execute(store.pool())
        .await
        .unwrap();
        store.migrate().await.unwrap();
        let (latency_ms, ttfb_ms): (i64, Option<i64>) =
            ::sqlx::query_as("SELECT latency_ms, ttfb_ms FROM llm_call_samples WHERE id = 'row-ttfb'")
                .fetch_one(store.pool())
                .await
                .unwrap();
        assert_eq!(latency_ms, 17_600, "the old row is preserved");
        assert_eq!(
            ttfb_ms, None,
            "pre-0006 rows keep ttfb_ms NULL — excluded from the average, never treated as 0"
        );

        // A row that DOES carry a measurement round-trips through the driver,
        // which is what the write path (`insert_llm_sample`) produces.
        ::sqlx::query(
            "INSERT INTO llm_call_samples (id, provider, model, latency_ms, ttfb_ms, success, attempt, created_at) \
             VALUES ('row-ttfb-2', 'deepseek', 'deepseek-v4-flash', 17600, 310, 1, 1, '2026-09-14T10:01:00.000000Z')",
        )
        .execute(store.pool())
        .await
        .unwrap();
        let ttfb: Option<i64> = ::sqlx::query_scalar("SELECT ttfb_ms FROM llm_call_samples WHERE id = 'row-ttfb-2'")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(ttfb, Some(310), "a measured ttfb round-trips");
    }

    /// 0005 (RENG-75), the other half: the `llm_providers.provider` UNIQUE index
    /// from 0001 (which made a second same-named card impossible to store) is
    /// dropped, so the identity change can actually be persisted — two cards
    /// sharing a name survive a `replace_llm_providers` round trip in order.
    /// Without the drop this is a 500 on `PUT /config`
    /// (`insert llm_provider "…"`), measured against the real server.
    #[tokio::test]
    async fn migrate_0005_drops_the_provider_name_unique_index() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let indexes: Vec<String> = ::sqlx::query_scalar("SELECT name FROM sqlite_master WHERE type='index'")
            .fetch_all(store.pool())
            .await
            .unwrap();
        assert!(
            !indexes.iter().any(|i| i == "idx_llm_providers_provider"),
            "the provider-name unique index must be gone: {indexes:?}"
        );
        // Idempotent: a repeated migrate (a restart of the upgraded binary)
        // keeps the schema as it is.
        store.migrate().await.unwrap();

        let card = |key: &str, max_tokens: u32| crate::models::LLMConfig {
            provider: "acme-pay".to_string(),
            model: "m1".to_string(),
            api_key: key.to_string(),
            api_base: "https://api.acme.example/v1".to_string(),
            max_tokens,
            temperature: 0.7,
            disable_thinking: None,
            disabled: false,
        };
        let stored = vec![card("sk-acct-a", 4096), card("sk-acct-b", 2048)];
        crate::store::traits::ConfigStore::replace_llm_providers(&store, &stored)
            .await
            .expect("two same-named cards must be storable (0005 drops the UNIQUE index)");

        let loaded = crate::store::traits::ConfigStore::load_llm_providers(&store)
            .await
            .unwrap();
        assert_eq!(loaded.len(), 2, "both cards come back");
        assert_eq!(loaded[0].provider, loaded[1].provider, "the shared display name");
        assert_eq!(loaded[0].api_key, "sk-acct-a", "each card keeps its own key");
        assert_eq!(loaded[1].api_key, "sk-acct-b");
        assert_eq!(
            loaded.iter().map(|c| c.max_tokens).collect::<Vec<_>>(),
            vec![4096, 2048],
            "stored order (raw.position), never re-sorted by name"
        );
    }

    /// RENG-57 (c): 0004 is additive — an instance that already holds review
    /// history keeps every row when the upgraded binary re-runs its embedded
    /// migrator at startup, and no historical sample is invented (a review
    /// that ran before 0.10.23 has no call-level timing to backfill).
    #[tokio::test]
    async fn llm_call_samples_migration_leaves_existing_rows_alone() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        // A review as the pre-RENG-57 schema held it (llm_summary is the
        // review-level snapshot RENG-38 wrote; there was no sample table).
        let entry = TaskEntry {
            task_id: Uuid::new_v4(),
            state: crate::server::task_queue::TaskState::Completed,
            created_at: Utc::now(),
            started_at: None,
            completed_at: None,
            result: None,
            error: None,
            request: None,
            source_meta: Default::default(),
            progress: None,
            expert_name: None,
            llm_summary: Some(r#"[{"provider":"xiaomi","model":"mimo"}]"#.to_string()),
        };
        crate::store::traits::ReviewStore::create(&store, &entry).await.unwrap();

        // What a restart of the upgraded binary does: run the migrator again.
        store.migrate().await.unwrap();

        let (state, summary): (String, Option<String>) =
            ::sqlx::query_as("SELECT state, llm_summary FROM reviews WHERE task_id = ?")
                .bind(entry.task_id.to_string())
                .fetch_one(store.pool())
                .await
                .unwrap();
        assert_eq!(state, "completed");
        assert_eq!(summary.as_deref(), Some(r#"[{"provider":"xiaomi","model":"mimo"}]"#));
        let samples: i64 = ::sqlx::query_scalar("SELECT COUNT(*) FROM llm_call_samples")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(samples, 0, "no sample can be backfilled for past calls");
    }

    /// 验证点 A(b): `?` placeholder INSERT + SELECT round trip on SQLite
    /// through the Any driver.
    #[tokio::test]
    async fn question_mark_placeholders_round_trip() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        ::sqlx::query(
            "INSERT INTO reviews (task_id, state, source_meta, project, repository, created_at) \
             VALUES (?, ?, ?, ?, ?, ?)",
        )
        .bind("00000000-0000-0000-0000-0000000000ab")
        .bind("pending")
        .bind("{}")
        .bind("group/proj")
        .bind("proj")
        .bind(encode_ts(&Utc::now()))
        .execute(store.pool())
        .await
        .unwrap();

        let (task_id, state, project): (String, String, Option<String>) =
            ::sqlx::query_as("SELECT task_id, state, project FROM reviews WHERE task_id = ?")
                .bind("00000000-0000-0000-0000-0000000000ab")
                .fetch_one(store.pool())
                .await
                .unwrap();
        assert_eq!(task_id, "00000000-0000-0000-0000-0000000000ab");
        assert_eq!(state, "pending");
        assert_eq!(project.as_deref(), Some("group/proj"));
    }

    /// 验证点 D: timestamps (chrono-generated, RFC 3339 TEXT because the Any
    /// driver has no chrono `Type` impls) round-trip losslessly and
    /// `ORDER BY created_at` returns chronological order.
    #[tokio::test]
    async fn datetime_binding_round_trip_and_ordering() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let t1 = Utc.with_ymd_and_hms(2026, 9, 3, 10, 0, 0).unwrap();
        let t2 = Utc.with_ymd_and_hms(2026, 9, 3, 10, 0, 1).unwrap();
        let t3 = Utc.with_ymd_and_hms(2026, 9, 3, 9, 59, 59).unwrap();

        // Insert out of order on purpose.
        for (id, ts) in [("b", t2), ("a", t1), ("c", t3)] {
            ::sqlx::query("INSERT INTO reviews (task_id, state, created_at) VALUES (?, ?, ?)")
                .bind(id)
                .bind("completed")
                .bind(encode_ts(&ts))
                .execute(store.pool())
                .await
                .unwrap();
        }

        // The stored representation itself must be the RFC 3339 UTC string —
        // lexicographic order on it is the pagination premise.
        let raw: String = ::sqlx::query_scalar("SELECT created_at FROM reviews WHERE task_id = 'a'")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(raw, "2026-09-03T10:00:00.000000Z");

        let rows: Vec<(String, String)> =
            ::sqlx::query_as("SELECT task_id, created_at FROM reviews ORDER BY created_at")
                .fetch_all(store.pool())
                .await
                .unwrap();
        let ids: Vec<&str> = rows.iter().map(|(id, _)| id.as_str()).collect();
        assert_eq!(ids, vec!["c", "a", "b"], "chronological order expected");
        // Round-trip fidelity: decoded value must equal the original.
        assert_eq!(decode_ts(&rows[1].1).unwrap(), t1);
    }

    /// 验证点 A(a) on the PG side: requires a live PostgreSQL via
    /// `DATABASE_URL`. Run explicitly with:
    /// `DATABASE_URL=postgres://... cargo test store -- --ignored`
    ///
    /// Verifies: migrate on an AnyPool against PG (incl. the
    /// `_sqlx_migrations` ledger), idempotent re-run, and the store-layer
    /// `?` → `$1..$n` placeholder rewrite ([`SqlxStore::sql`]). Timestamps
    /// are TEXT columns bound as RFC 3339 strings (Any driver constraint),
    /// so the read-back is a plain String round trip.
    #[tokio::test]
    #[ignore = "requires DATABASE_URL pointing at a scratch PostgreSQL"]
    async fn migrate_on_postgres_smoke() {
        let url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
        let store = SqlxStore::connect(&url).await.unwrap();
        store.migrate().await.unwrap();
        // Idempotent second run.
        store.migrate().await.unwrap();

        // `?` placeholders are rewritten by the store layer, not the driver.
        let now = Utc::now();
        let insert = store.sql("INSERT INTO reviews (task_id, state, created_at) VALUES (?, ?, ?)");
        ::sqlx::query(&insert)
            .bind("pg-smoke-0001")
            .bind("pending")
            .bind(encode_ts(&now))
            .execute(store.pool())
            .await
            .unwrap();
        let select = store.sql("SELECT created_at FROM reviews WHERE task_id = ?");
        let back: String = ::sqlx::query_scalar(&select)
            .bind("pg-smoke-0001")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(decode_ts(&back).unwrap(), now);
        let delete = store.sql("DELETE FROM reviews WHERE task_id = ?");
        ::sqlx::query(&delete)
            .bind("pg-smoke-0001")
            .execute(store.pool())
            .await
            .unwrap();
    }
}
