//! Persistence layer (0.10.0).
//!
//! One `sqlx::AnyPool` serves both PostgreSQL (primary, via `DATABASE_URL`)
//! and embedded SQLite (fallback). All SQL lives behind this module; the
//! dialect rules of `design/persistence.md` §3.1 apply everywhere:
//!
//! - placeholders are always `?` (the Any driver translates them for PG);
//! - no `RETURNING` (primary keys are Rust-side UUIDs);
//! - JSON columns are `TEXT`, serialized/deserialized by the store layer;
//! - timestamps are generated by chrono on the Rust side, never by DDL
//!   defaults. NOTE (finding from verification point A/D): the `Any` driver
//!   has no `Type<Any>` impls for chrono types — only bool/int/float/str/blob
//!   are supported — and SQLite refuses `String` decode from a column
//!   declared `TIMESTAMP`. Timestamp columns are therefore declared `TEXT`
//!   and carry fixed-width RFC 3339 UTC strings
//!   (`2026-09-03T10:00:00.000000Z`), encoded/decoded by the store layer.
//!   Fixed-width UTC `Z` formatting keeps lexicographic order ==
//!   chronological order, which `ORDER BY created_at` pagination relies on.
//!
//! Shipped so far: connection/migration skeleton, verification-point-A/D
//! smoke tests, and the configuration domain ([`traits::ConfigStore`]
//! implemented on [`SqlxStore`] in [`sqlx`], row codecs + the `enc:`
//! boundary in [`rows`]). `ReviewStore` / `DiscussionStore` land in later
//! steps.

pub mod rows;
pub mod sqlx;
pub mod traits;

use std::path::Path;

use anyhow::{Context, Result};
use chrono::{DateTime, SecondsFormat, Utc};

/// Embedded migrations (compiled in via `sqlx::migrate!`).
static MIGRATOR: ::sqlx::migrate::Migrator = ::sqlx::migrate!("./migrations");

/// Which storage backend a [`SqlxStore`] pool talks to, recorded at connect
/// time from the URL (design/persistence.md §4.3). Surfaced read-only via
/// `GET /api/v1/system/health` as `storage_backend`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendKind {
    /// `postgres://` / `postgresql://` URL.
    Postgresql,
    /// Everything else (embedded SQLite, incl. in-memory).
    Sqlite,
}

impl BackendKind {
    /// Wire value exposed to the API layer (`"postgresql"` / `"sqlite"`).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Postgresql => "postgresql",
            Self::Sqlite => "sqlite",
        }
    }
}

/// URL discrimination per design/persistence.md §4.3: `postgres://` /
/// `postgresql://` → PostgreSQL; anything else → SQLite.
fn backend_kind_of(url: &str) -> BackendKind {
    if url.starts_with("postgres://") || url.starts_with("postgresql://") {
        BackendKind::Postgresql
    } else {
        BackendKind::Sqlite
    }
}

/// SQLx store backed by an `Any` pool (PostgreSQL or SQLite).
///
/// Besides pool construction / SQLite pragmas / migrations, the store holds
/// the at-rest encryption key (`secrets.key`, per config dir): the `enc:`
/// boundary lives in [`rows`], and PG deployments still read the key from
/// the server-local config dir (design/persistence.md §6.2).
#[derive(Debug, Clone)]
pub struct SqlxStore {
    pool: ::sqlx::AnyPool,
    kind: BackendKind,
    pub(crate) key: [u8; 32],
}

impl SqlxStore {
    /// Connect to the database identified by `url`.
    ///
    /// URL discrimination (design/persistence.md §4.3):
    /// - `postgres://` / `postgresql://` → PostgreSQL;
    /// - anything else → SQLite.
    ///
    /// For SQLite, after the pool is built the connection pragmas required by
    /// the schema are applied: WAL journal, foreign keys on, 5 s busy timeout.
    /// The secrets key resolves via the standard config-dir resolution
    /// (`persist::resolve_ui_state_path` → `key_path_for`).
    pub async fn connect(url: &str) -> Result<Self> {
        let state_path = crate::server::api::config::persist::resolve_ui_state_path()
            .context("cannot resolve the config dir for the secrets key")?;
        let key = crate::config::secrets::load_or_create_key(&crate::config::secrets::key_path_for(&state_path))?;
        Self::connect_with_key(url, key).await
    }

    /// Connect with an explicit secrets key (used by [`Self::connect`] and
    /// available to tests that need a stable key without a config dir).
    pub async fn connect_with_key(url: &str, key: [u8; 32]) -> Result<Self> {
        ::sqlx::any::install_default_drivers();
        let kind = backend_kind_of(url);
        let pool = ::sqlx::any::AnyPoolOptions::new().connect(url).await.with_context(|| {
            format!(
                "failed to connect to database ({url_scheme})",
                url_scheme = scheme_of(url)
            )
        })?;
        if kind == BackendKind::Sqlite {
            apply_sqlite_pragmas(&pool).await?;
        }
        Ok(Self { pool, kind, key })
    }

    /// Connect to the default embedded SQLite database under `config_dir`
    /// (`sqlite://{config_dir}/review.db?mode=rwc`, created on demand); the
    /// secrets key is `{config_dir}/secrets.key`, created on first use.
    pub async fn connect_default(config_dir: &Path) -> Result<Self> {
        std::fs::create_dir_all(config_dir)
            .with_context(|| format!("failed to create config dir {}", config_dir.display()))?;
        let key = crate::config::secrets::load_or_create_key(
            &config_dir.join(crate::config::secrets::SECRETS_KEY_FILE_NAME),
        )?;
        let url = format!("sqlite://{}/review.db?mode=rwc", config_dir.display());
        Self::connect_with_key(&url, key).await
    }

    /// In-memory SQLite store for unit tests.
    ///
    /// `max_connections(1)` is mandatory: with a larger pool each connection
    /// would be an independent in-memory database. Uses an ephemeral random
    /// key — enough for round-trip tests, but nothing persists between
    /// instances.
    pub async fn new_in_memory() -> Result<Self> {
        let mut key = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut key);
        ::sqlx::any::install_default_drivers();
        let pool = ::sqlx::any::AnyPoolOptions::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .context("failed to open in-memory sqlite database")?;
        apply_sqlite_pragmas(&pool).await?;
        Ok(Self {
            pool,
            kind: BackendKind::Sqlite,
            key,
        })
    }

    /// Apply the embedded migrations (idempotent — already-applied
    /// migrations are skipped based on the `_sqlx_migrations` ledger).
    pub async fn migrate(&self) -> Result<()> {
        MIGRATOR.run(&self.pool).await.context("database migration failed")?;
        Ok(())
    }

    /// The storage backend this pool talks to, recorded at connect time
    /// (PostgreSQL or SQLite).
    pub fn backend_kind(&self) -> BackendKind {
        self.kind
    }

    /// Access the underlying pool (used by trait implementations in
    /// [`sqlx`] and by tests).
    pub fn pool(&self) -> &::sqlx::AnyPool {
        &self.pool
    }
}

/// Scheme prefix of a database URL, for error messages that must not leak
/// credentials embedded in the URL.
fn scheme_of(url: &str) -> &str {
    url.split("://").next().unwrap_or(url)
}

async fn apply_sqlite_pragmas(pool: &::sqlx::AnyPool) -> Result<()> {
    // Executed as separate statements: Any queries are single-statement.
    for pragma in [
        "PRAGMA journal_mode=WAL;",
        "PRAGMA foreign_keys=ON;",
        "PRAGMA busy_timeout=5000;",
    ] {
        ::sqlx::query(pragma)
            .execute(pool)
            .await
            .with_context(|| format!("failed to apply {pragma}"))?;
    }
    Ok(())
}

/// Encode a timestamp for a `TEXT` timestamp column. The Any driver has no
/// chrono `Type` impls, so values cross as fixed-width RFC 3339 UTC strings
/// (`2026-09-03T10:00:00.000000Z`); lexicographic order == chronological
/// order, which `ORDER BY created_at` pagination relies on.
pub(crate) fn encode_ts(ts: &DateTime<Utc>) -> String {
    ts.to_rfc3339_opts(SecondsFormat::Micros, true)
}

/// Decode a timestamp produced by [`encode_ts`]. Used by the review-domain
/// codecs ([`rows`]) and by tests.
pub(crate) fn decode_ts(s: &str) -> Result<DateTime<Utc>> {
    Ok(DateTime::parse_from_rfc3339(s)
        .with_context(|| format!("invalid RFC 3339 timestamp in database: {s:?}"))?
        .with_timezone(&Utc))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ::sqlx::Row;
    use chrono::TimeZone;

    /// URL discrimination per §4.3: `postgres://` / `postgresql://` →
    /// PostgreSQL, everything else → SQLite. Pure-function-level coverage of
    /// the `"postgresql"` wire value (a live PG is not available in unit
    /// tests; the end-to-end PG smoke test is `migrate_on_postgres_smoke`).
    #[test]
    fn backend_kind_discriminates_by_url_scheme() {
        assert_eq!(
            backend_kind_of("postgres://u:p@db.example/review"),
            BackendKind::Postgresql
        );
        assert_eq!(
            backend_kind_of("postgresql://u:p@db.example/review"),
            BackendKind::Postgresql
        );
        assert_eq!(BackendKind::Postgresql.as_str(), "postgresql");

        assert_eq!(backend_kind_of("sqlite:///tmp/review.db?mode=rwc"), BackendKind::Sqlite);
        assert_eq!(backend_kind_of("sqlite::memory:"), BackendKind::Sqlite);
        assert_eq!(BackendKind::Sqlite.as_str(), "sqlite");
    }

    /// An in-memory SQLite store reports the sqlite backend kind.
    #[tokio::test]
    async fn in_memory_store_reports_sqlite_backend_kind() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        assert_eq!(store.backend_kind(), BackendKind::Sqlite);
        assert_eq!(store.backend_kind().as_str(), "sqlite");
    }

    /// 验证点 A(a): in-memory SQLite + migrate creates the schema, and a
    /// second migrate run is an idempotent no-op.
    #[tokio::test]
    async fn migrate_creates_schema_and_is_idempotent() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let tables: Vec<String> = ::sqlx::query(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
        )
        .fetch_all(store.pool())
        .await
        .unwrap()
        .into_iter()
        .map(|row| row.get::<String, _>(0))
        .collect();
        for expected in [
            "app_settings",
            "expert_reports",
            "git_platforms",
            "llm_providers",
            "mr_discussions",
            "review_contexts",
            "reviews",
        ] {
            assert!(
                tables.iter().any(|t| t == expected),
                "missing table {expected}, got {tables:?}"
            );
        }

        // Second run: must succeed and apply nothing new.
        store.migrate().await.unwrap();
        let applied: i64 = ::sqlx::query_scalar("SELECT COUNT(*) FROM _sqlx_migrations")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(applied, 1, "only 0001_init should be recorded");
    }

    /// 验证点 A(b): `?` placeholder INSERT + SELECT round trip on SQLite
    /// through the Any driver.
    #[tokio::test]
    async fn question_mark_placeholders_round_trip() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        ::sqlx::query(
            "INSERT INTO reviews (task_id, state, source_meta, project, repository, created_at) \
             VALUES (?, ?, ?, ?, ?, ?)",
        )
        .bind("00000000-0000-0000-0000-0000000000ab")
        .bind("pending")
        .bind("{}")
        .bind("group/proj")
        .bind("proj")
        .bind(encode_ts(&Utc::now()))
        .execute(store.pool())
        .await
        .unwrap();

        let (task_id, state, project): (String, String, Option<String>) =
            ::sqlx::query_as("SELECT task_id, state, project FROM reviews WHERE task_id = ?")
                .bind("00000000-0000-0000-0000-0000000000ab")
                .fetch_one(store.pool())
                .await
                .unwrap();
        assert_eq!(task_id, "00000000-0000-0000-0000-0000000000ab");
        assert_eq!(state, "pending");
        assert_eq!(project.as_deref(), Some("group/proj"));
    }

    /// 验证点 D: timestamps (chrono-generated, RFC 3339 TEXT because the Any
    /// driver has no chrono `Type` impls) round-trip losslessly and
    /// `ORDER BY created_at` returns chronological order.
    #[tokio::test]
    async fn datetime_binding_round_trip_and_ordering() {
        let store = SqlxStore::new_in_memory().await.unwrap();
        store.migrate().await.unwrap();

        let t1 = Utc.with_ymd_and_hms(2026, 9, 3, 10, 0, 0).unwrap();
        let t2 = Utc.with_ymd_and_hms(2026, 9, 3, 10, 0, 1).unwrap();
        let t3 = Utc.with_ymd_and_hms(2026, 9, 3, 9, 59, 59).unwrap();

        // Insert out of order on purpose.
        for (id, ts) in [("b", t2), ("a", t1), ("c", t3)] {
            ::sqlx::query("INSERT INTO reviews (task_id, state, created_at) VALUES (?, ?, ?)")
                .bind(id)
                .bind("completed")
                .bind(encode_ts(&ts))
                .execute(store.pool())
                .await
                .unwrap();
        }

        // The stored representation itself must be the RFC 3339 UTC string —
        // lexicographic order on it is the pagination premise.
        let raw: String = ::sqlx::query_scalar("SELECT created_at FROM reviews WHERE task_id = 'a'")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(raw, "2026-09-03T10:00:00.000000Z");

        let rows: Vec<(String, String)> =
            ::sqlx::query_as("SELECT task_id, created_at FROM reviews ORDER BY created_at")
                .fetch_all(store.pool())
                .await
                .unwrap();
        let ids: Vec<&str> = rows.iter().map(|(id, _)| id.as_str()).collect();
        assert_eq!(ids, vec!["c", "a", "b"], "chronological order expected");
        // Round-trip fidelity: decoded value must equal the original.
        assert_eq!(decode_ts(&rows[1].1).unwrap(), t1);
    }

    /// 验证点 A(a) on the PG side: requires a live PostgreSQL via
    /// `DATABASE_URL`. Run explicitly with:
    /// `DATABASE_URL=postgres://... cargo test store -- --ignored`
    ///
    /// Verifies: migrate on an AnyPool against PG (incl. the
    /// `_sqlx_migrations` ledger), idempotent re-run, and `?` placeholder
    /// translation. Timestamps are TEXT columns bound as RFC 3339 strings
    /// (Any driver constraint), so the read-back is a plain String round trip.
    #[tokio::test]
    #[ignore = "requires DATABASE_URL pointing at a scratch PostgreSQL"]
    async fn migrate_on_postgres_smoke() {
        let url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
        let store = SqlxStore::connect(&url).await.unwrap();
        store.migrate().await.unwrap();
        // Idempotent second run.
        store.migrate().await.unwrap();

        // `?` placeholders must be translated by the Any driver.
        let now = Utc::now();
        ::sqlx::query("INSERT INTO reviews (task_id, state, created_at) VALUES (?, ?, ?)")
            .bind("pg-smoke-0001")
            .bind("pending")
            .bind(encode_ts(&now))
            .execute(store.pool())
            .await
            .unwrap();
        let back: String = ::sqlx::query_scalar("SELECT created_at FROM reviews WHERE task_id = ?")
            .bind("pg-smoke-0001")
            .fetch_one(store.pool())
            .await
            .unwrap();
        assert_eq!(decode_ts(&back).unwrap(), now);
        ::sqlx::query("DELETE FROM reviews WHERE task_id = ?")
            .bind("pg-smoke-0001")
            .execute(store.pool())
            .await
            .unwrap();
    }
}
