use super::*;

fn init_git_repo(path: &Path) {
    let run = |args: &[&str]| {
        let status = std::process::Command::new("git")
            .arg("-C")
            .arg(path)
            .args(args)
            .status()
            .expect("git command failed to run");
        assert!(status.success(), "git command {:?} failed", args);
    };
    run(&["init", "--initial-branch=main"]);
    run(&["config", "user.email", "test@example.com"]);
    run(&["config", "user.name", "Test User"]);
}

fn commit_all(path: &Path) {
    let run = |args: &[&str]| {
        let status = std::process::Command::new("git")
            .arg("-C")
            .arg(path)
            .args(args)
            .status()
            .expect("git command failed to run");
        assert!(status.success(), "git command {:?} failed", args);
    };
    run(&["add", "-A"]);
    run(&["commit", "-m", "test commit"]);
}

#[test]
fn test_scanner_ignores_node_modules() {
    let scanner = RepoScanner::new(".");
    assert!(scanner.is_ignored(Path::new("node_modules")));
    assert!(scanner.is_ignored(Path::new(".git")));
    assert!(!scanner.is_ignored(Path::new("src")));
}

#[test]
fn test_detect_language() {
    let scanner = RepoScanner::new(".");
    assert_eq!(scanner.detect_language("rs"), "Rust");
    assert_eq!(scanner.detect_language("py"), "Python");
    assert_eq!(scanner.detect_language("md"), "Documentation");
}

#[test]
fn test_is_binary_file() {
    let scanner = RepoScanner::new(".");
    assert!(scanner.is_binary_file("png"));
    assert!(scanner.is_binary_file("pdf"));
    assert!(!scanner.is_binary_file("rs"));
}

#[test]
fn test_compute_stats() {
    let entries = vec![
        FileEntry {
            path: "a.rs".to_string(),
            language: "Rust".to_string(),
            loc: 100,
            is_binary: false,
            is_generated: false,
        },
        FileEntry {
            path: "b.rs".to_string(),
            language: "Rust".to_string(),
            loc: 600,
            is_binary: false,
            is_generated: false,
        },
        FileEntry {
            path: "c.py".to_string(),
            language: "Python".to_string(),
            loc: 50,
            is_binary: false,
            is_generated: false,
        },
    ];
    let scanner = RepoScanner::new(".");
    let stats = scanner.compute_stats(&entries);
    assert_eq!(stats.total_files, 3);
    assert_eq!(stats.total_loc, 750);
    assert_eq!(stats.languages.get("Rust").unwrap().loc, 700);
    assert_eq!(stats.large_files.len(), 1);
}

#[test]
fn classify_file_detects_binary_files_from_extension() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("logo.png");
    std::fs::write(&path, "not actually binary").unwrap();
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    assert!(scanner.classify_file(&path).is_none());
}

#[test]
fn classify_file_detects_generated_files_by_name() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("Cargo.lock");
    std::fs::write(&path, "dummy lock\n").unwrap();
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entry = scanner.classify_file(&path).unwrap();
    assert!(entry.is_generated);
}

#[test]
fn classify_file_detects_generated_files_by_content_marker() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("api.pb.rs");
    std::fs::write(&path, "// Code generated by protoc. DO NOT EDIT.\nstruct Foo;\n").unwrap();
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entry = scanner.classify_file(&path).unwrap();
    assert!(entry.is_generated);
}

#[test]
fn classify_file_skips_hidden_files() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join(".hidden.rs");
    std::fs::write(&path, "fn main() {}").unwrap();
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    assert!(scanner.classify_file(&path).is_none());
}

#[test]
fn classify_file_sets_language_by_extension() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("main.rs");
    std::fs::write(&path, "fn main() {}\n").unwrap();
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entry = scanner.classify_file(&path).unwrap();
    assert_eq!(entry.language, "Rust");
    assert!(!entry.is_binary);
}

#[test]
fn is_generated_content_detects_common_markers() {
    let scanner = RepoScanner::new(".");
    assert!(scanner.is_generated_content("// Code generated by protoc"));
    assert!(scanner.is_generated_content("# autogenerated: do not touch"));
    assert!(scanner.is_generated_content("This file is auto-generated."));
    assert!(scanner.is_generated_content("Generated by Swagger Codegen."));
    assert!(scanner.is_generated_content("// DO NOT EDIT manually"));
    assert!(!scanner.is_generated_content("// Hand-written code"));
}

#[test]
fn test_git_repo_respects_gitignore() {
    let dir = tempfile::tempdir().unwrap();
    init_git_repo(dir.path());

    std::fs::write(dir.path().join(".gitignore"), "ignored.rs\n").unwrap();
    std::fs::write(dir.path().join("kept.rs"), "fn main() {}\n").unwrap();
    std::fs::write(dir.path().join("ignored.rs"), "fn ignored() {}\n").unwrap();

    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entries = scanner.scan().unwrap();

    let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();
    assert!(
        paths.iter().any(|p| p.ends_with("kept.rs")),
        "kept.rs should be included"
    );
    assert!(
        !paths.iter().any(|p| p.ends_with("ignored.rs")),
        "ignored.rs should be excluded by .gitignore"
    );
}

#[test]
fn test_scanner_skips_submodules() {
    let dir = tempfile::tempdir().unwrap();
    let mut scanner = RepoScanner::new(dir.path().to_str().unwrap());
    scanner.ignore_patterns.push("submodule".to_string());

    std::fs::create_dir_all(dir.path().join("submodule")).unwrap();
    std::fs::write(dir.path().join("submodule/foo.rs"), "fn foo() {}\n").unwrap();

    let entries = scanner.scan().unwrap();
    assert!(
        !entries.iter().any(|e| e.path.contains("submodule")),
        "submodule contents should be skipped"
    );
}

#[test]
fn test_scanner_skips_binary_files() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("logo.png"), "not actually binary").unwrap();
    std::fs::write(dir.path().join("main.rs"), "fn main() {}\n").unwrap();

    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entries = scanner.scan().unwrap();

    assert!(
        !entries.iter().any(|e| e.path.ends_with("logo.png")),
        "binary files should be skipped"
    );
    assert!(
        entries.iter().any(|e| e.path.ends_with("main.rs")),
        "text files should be included"
    );
}

#[test]
fn test_git_submodules_parsing() {
    let dir = tempfile::tempdir().unwrap();
    init_git_repo(dir.path());
    std::fs::create_dir_all(dir.path().join("nested")).unwrap();
    std::fs::write(dir.path().join("nested/file.rs"), "fn foo() {}\n").unwrap();

    let submodules = git_submodules(dir.path());
    assert!(
        submodules.is_empty(),
        "repo without submodules should return empty list"
    );
}

#[test]
fn test_path_matches_prefix() {
    assert!(path_matches_prefix("sub", "sub"));
    assert!(path_matches_prefix("sub/foo.rs", "sub"));
    assert!(!path_matches_prefix("subfoo.rs", "sub"));
    assert!(!path_matches_prefix("other/foo.rs", "sub"));
}

#[test]
fn test_scan_nonexistent_path_errors() {
    let dir = tempfile::tempdir().unwrap();
    let missing = dir.path().join("does-not-exist");
    let scanner = RepoScanner::new(missing.to_str().unwrap());

    let err = scanner.scan().expect_err("scan of a missing path must fail");
    assert!(
        err.to_string().contains("Repository path does not exist"),
        "unexpected error: {err:?}"
    );
}

/// Regression (feedback A): `git ls-files --cached` reads the index, so a
/// file deleted from the worktree but not yet staged (`rm` without
/// `git rm`) was scanned as a phantom 0-LOC entry. The worktree is the
/// source of truth — the file must not appear in the scan results.
#[test]
fn scan_skips_file_deleted_from_worktree_but_still_in_index() {
    let dir = tempfile::tempdir().unwrap();
    init_git_repo(dir.path());
    std::fs::write(dir.path().join("kept.rs"), "fn kept() {}\n").unwrap();
    std::fs::write(dir.path().join("gone.rs"), "fn gone() {}\n").unwrap();
    commit_all(dir.path());

    // Delete from the worktree only; the index still lists the file.
    std::fs::remove_file(dir.path().join("gone.rs")).unwrap();

    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entries = scanner.scan().unwrap();
    let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();

    assert!(
        paths.iter().any(|p| p.ends_with("kept.rs")),
        "kept.rs should be scanned: {paths:?}"
    );
    assert!(
        !paths.iter().any(|p| p.ends_with("gone.rs")),
        "gone.rs is deleted from the worktree and must not be scanned: {paths:?}"
    );
}

/// Regression (feedback B): CI configs were dropped by the dotfile
/// filter and never reached the scan results. `.gitlab-ci.yml` and
/// `.travis.yml` are whitelisted, and dot-directories like `.circleci/`
/// are descended into, so their configs become scan entries.
#[test]
fn scan_includes_ci_config_files() {
    let dir = tempfile::tempdir().unwrap();
    init_git_repo(dir.path());
    std::fs::write(dir.path().join(".gitlab-ci.yml"), "stages:\n  - test\n").unwrap();
    std::fs::write(dir.path().join(".travis.yml"), "script: cargo test\n").unwrap();
    std::fs::create_dir_all(dir.path().join(".circleci")).unwrap();
    std::fs::write(
        dir.path().join(".circleci/config.yml"),
        "jobs:\n  test:\n    steps: []\n",
    )
    .unwrap();
    std::fs::write(dir.path().join(".hidden.rs"), "fn hidden() {}\n").unwrap();

    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entries = scanner.scan().unwrap();
    let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();

    assert!(
        paths.iter().any(|p| p.ends_with(".gitlab-ci.yml")),
        ".gitlab-ci.yml should be scanned: {paths:?}"
    );
    assert!(
        paths.iter().any(|p| p.ends_with(".travis.yml")),
        ".travis.yml should be scanned: {paths:?}"
    );
    assert!(
        paths.iter().any(|p| p.ends_with(".circleci/config.yml")),
        ".circleci/config.yml should be scanned: {paths:?}"
    );
    assert!(
        !paths.iter().any(|p| p.ends_with(".hidden.rs")),
        "non-whitelisted dotfiles stay excluded: {paths:?}"
    );
}

/// Same as above for the non-Git fallback: `scan_dir` must descend into
/// dot-directories (only names in `ignore_patterns` are pruned).
#[test]
fn scan_dir_descends_into_dot_directories() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join(".circleci")).unwrap();
    std::fs::write(dir.path().join(".circleci/config.yml"), "jobs: {}\n").unwrap();
    std::fs::write(dir.path().join(".gitlab-ci.yml"), "stages:\n  - test\n").unwrap();

    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    let entries = scanner.scan().unwrap();
    let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();

    assert!(
        paths.iter().any(|p| p.ends_with(".circleci/config.yml")),
        ".circleci/config.yml should be scanned: {paths:?}"
    );
    assert!(
        paths.iter().any(|p| p.ends_with(".gitlab-ci.yml")),
        ".gitlab-ci.yml should be scanned: {paths:?}"
    );
}

/// Contract: an unreadable/missing file yields `None`, not a 0-LOC entry.
#[test]
fn classify_file_returns_none_for_missing_file() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("ghost.rs"); // never created on disk
    let scanner = RepoScanner::new(dir.path().to_str().unwrap());
    assert!(scanner.classify_file(&path).is_none());
}
