//! Core data models shared throughout the review engine.
//!
//! Re-exports types from three private submodules: `config` (application
//! configuration structures including [`AppConfig`], [`LLMConfig`],
//! [`ScoringConfig`]), `expert` (expert definitions, triggers, and
//! report types like [`ExpertReport`], [`AggregatedReport`],
//! [`GlobalReviewContext`]), and `finding` (review findings with
//! severity, confidence, line numbers, and recommendations). Also
//! defines top-level enums and structs such as [`RiskLevel`],
//! [`OverallAssessment`], [`Severity`], and [`ReviewInput`].

mod config;
mod expert;
mod finding;
mod git_platform;

pub use config::*;
pub use expert::*;
pub use finding::*;
pub use git_platform::*;

use serde::{Deserialize, Serialize};

// ─── Risk Level & Overall Assessment ───────────

/// Overall risk level for a review.
///
/// Ordered from least to most severe: `Healthy` (score above
/// `healthy_min`, default 91+) is the best band, `Critical` the worst.
#[derive(Debug, Clone, PartialEq, PartialOrd, Serialize, Deserialize, Default)]
pub enum RiskLevel {
    Healthy,
    Low,
    LowMedium,
    #[default]
    Medium,
    High,
    Critical,
}

impl std::fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RiskLevel::Healthy => write!(f, "healthy"),
            RiskLevel::Low => write!(f, "low"),
            RiskLevel::LowMedium => write!(f, "low-medium"),
            RiskLevel::Medium => write!(f, "medium"),
            RiskLevel::High => write!(f, "high"),
            RiskLevel::Critical => write!(f, "critical"),
        }
    }
}

impl std::str::FromStr for RiskLevel {
    type Err = String;

    /// Parse the lowercase `Display` form (e.g. "healthy", "low-medium").
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "healthy" => Ok(RiskLevel::Healthy),
            "low" => Ok(RiskLevel::Low),
            "low-medium" => Ok(RiskLevel::LowMedium),
            "medium" => Ok(RiskLevel::Medium),
            "high" => Ok(RiskLevel::High),
            "critical" => Ok(RiskLevel::Critical),
            other => Err(format!("unknown risk level: {other}")),
        }
    }
}

/// Serde adapter that serializes [`RiskLevel`] as its lowercase `Display`
/// string (e.g. `"healthy"`, `"low-medium"`) and parses it back.
///
/// The repo-review JSON contract has always used lowercase risk labels,
/// while the MR-review JSON keeps serde's default variant names. Attach
/// with `#[serde(with = "risk_level_lowercase")]` on repo-side fields to
/// keep that contract while sharing the enum.
pub mod risk_level_lowercase {
    use super::RiskLevel;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(level: &RiskLevel, serializer: S) -> Result<S::Ok, S::Error> {
        level.to_string().serialize(serializer)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<RiskLevel, D::Error> {
        let s = String::deserialize(deserializer)?;
        s.parse().map_err(serde::de::Error::custom)
    }
}

/// Overall assessment of a review, computed from expert scores.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OverallAssessment {
    /// Computed score (0-100).
    pub score: u8,
    /// Risk level derived from the score.
    pub risk_level: RiskLevel,
    /// Lead reviewer's override assessment (optional).
    pub lead_override: Option<String>,
    /// Summary of key findings.
    pub tl_dr: String,
    /// True when every expert reported zero findings. A perfect score with no
    /// findings is NOT evidence of quality — it may mean low coverage or a
    /// systemic miss — so reports must flag the result as **unverified**
    /// instead of presenting it as healthy.
    #[serde(default)]
    pub unverified: bool,
    /// True when demonstrated hunk coverage fell below the threshold (or zero
    /// findings made coverage untraceable). Kept separate from `unverified` so
    /// the report can say WHY the result is unverified (coverage vs. no
    /// findings). `unverified` is set when EITHER is true.
    #[serde(default)]
    pub coverage_insufficient: bool,
}

// ─── Global Review Context ────────────────────

/// High-level context for a PR review, generated by the lead reviewer expert.
///
/// Contains a summary, identified risk areas, files that need focused
/// attention, tailored guidance for domain-specific experts, and a
/// lightweight project-level overview.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlobalReviewContext {
    /// One-paragraph summary of the PR's purpose and scope.
    pub summary: String,
    /// List of risk areas identified (e.g. "Security: auth middleware changes").
    pub risk_areas: Vec<String>,
    /// Files that expert reviewers should prioritise.
    pub focus_files: Vec<String>,
    /// Tailored guidance for domain experts.
    pub guidance: String,
    /// Lightweight project-level overview generated from README, manifest, file tree, and git logs.
    #[serde(default)]
    pub project_overview: String,
}

impl GlobalReviewContext {
    /// Format the context as a Markdown section for inclusion in LLM prompts.
    ///
    /// Outputs two distinct sub-sections: a branch summary from the PR diff
    /// and branch commits, and a project overview from project-level context.
    pub fn to_prompt_section(&self) -> String {
        format!(
            "## Lead Context\n\n\
             ### Branch Summary\n\n\
             Summary: {}\n\n\
             Risk Areas: {}\n\n\
             Focus Files: {}\n\n\
             Guidance: {}\n\n\
             ### Project Overview\n\n\
             {}",
            self.summary,
            self.risk_areas.join(", "),
            self.focus_files.join(", "),
            self.guidance,
            self.project_overview,
        )
    }
}

#[cfg(test)]
mod global_review_context_tests {
    use super::*;

    #[test]
    fn test_to_prompt_section_has_branch_and_project_sections() {
        let ctx = GlobalReviewContext {
            summary: "Add auth".to_string(),
            risk_areas: vec!["Security".to_string()],
            focus_files: vec!["src/auth.rs".to_string()],
            guidance: "Check token handling".to_string(),
            project_overview: "Rust web service with axum".to_string(),
        };
        let section = ctx.to_prompt_section();
        assert!(section.contains("## Lead Context"));
        assert!(section.contains("### Branch Summary"));
        assert!(section.contains("### Project Overview"));
        assert!(section.contains("Add auth"));
        assert!(section.contains("Rust web service with axum"));
    }

    #[test]
    fn test_project_overview_defaults_on_deserialization() {
        let yaml = "summary: \"s\"\nrisk_areas: []\nfocus_files: []\nguidance: \"g\"\n";
        let ctx: GlobalReviewContext = serde_yaml_ng::from_str(yaml).unwrap();
        assert!(ctx.project_overview.is_empty());
    }
}

// ─── MR/PR 参与者 (RENG-42/43) ──────────────

/// A person involved in an MR/PR, as stored in `reviews.source_meta` and
/// surfaced in the History "participants" column (RENG-42). Field names and
/// the `snake_case` role strings are the persisted contract; the REST layer
/// re-maps them to camelCase (`ReviewParticipant`, RENG-44).
///
/// Ordering and de-duplication are produced by [`aggregate_participants`]:
/// `author` → `creator` → `participant`, one entry per person (highest role
/// wins), distinct robots always stay distinct.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Participant {
    /// Display name; falls back to `username` when the provider has no name.
    pub name: String,
    /// Provider handle (`alice`, GitHub login). Empty when unknown.
    #[serde(default)]
    pub username: String,
    /// Avatar URL; `None` when the provider does not return one.
    #[serde(default)]
    pub avatar_url: Option<String>,
    /// Why this person is in the list.
    pub role: ParticipantRole,
    /// Robot account (GitLab `*_bot` access-token users, GitHub `type: Bot`).
    #[serde(default)]
    pub bot: bool,
}

/// Role of a participant. Serialized `snake_case` as the persisted contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ParticipantRole {
    /// Head commit author — who wrote the code under review.
    Author,
    /// MR/PR opener.
    Creator,
    /// Any other participant (commenters, reviewers, robots).
    Participant,
}

impl ParticipantRole {
    /// De-dup precedence: `author > creator > participant`.
    pub fn priority(self) -> u8 {
        match self {
            ParticipantRole::Author => 2,
            ParticipantRole::Creator => 1,
            ParticipantRole::Participant => 0,
        }
    }
}

/// Pre-aggregation participant record. Carries the provider's numeric user id
/// so [`aggregate_participants`] can de-dup by id first, then username, then
/// display name — the public [`Participant`] contract keeps no id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParticipantInput {
    pub id: Option<u64>,
    pub name: String,
    pub username: String,
    pub avatar_url: Option<String>,
    pub role: ParticipantRole,
    pub bot: bool,
}

impl ParticipantInput {
    /// A record with only a display name and a role; the rest is filled in by
    /// the provider-specific builders below.
    pub fn new(name: impl Into<String>, role: ParticipantRole) -> Self {
        Self {
            id: None,
            name: name.into(),
            username: String::new(),
            avatar_url: None,
            role,
            bot: false,
        }
    }

    pub fn with_id(mut self, id: Option<u64>) -> Self {
        self.id = id;
        self
    }

    pub fn with_username(mut self, username: impl Into<String>) -> Self {
        let username = username.into();
        self.bot = self.bot || username_is_bot(&username);
        self.username = username;
        self
    }

    pub fn with_avatar(mut self, avatar_url: Option<String>) -> Self {
        self.avatar_url = avatar_url.filter(|u| !u.trim().is_empty());
        self
    }

    pub fn with_bot(mut self, bot: bool) -> Self {
        self.bot = self.bot || bot;
        self
    }
}

/// Whether a handle looks like a provider robot account. GitLab group /
/// project access tokens create users shaped like `group_1_bot`; GitHub marks
/// bots with `user.type == "Bot"` (the caller ORs that flag in).
pub fn username_is_bot(username: &str) -> bool {
    username.trim().to_ascii_lowercase().ends_with("_bot")
}

/// Same-person test for aggregation: id when both sides have one (a mismatch
/// means different people even with an equal name), else username, else
/// display name — all case-insensitive.
fn is_same_person(a: &ParticipantInput, b: &ParticipantInput) -> bool {
    if let (Some(ia), Some(ib)) = (a.id, b.id) {
        return ia == ib;
    }
    let (au, bu) = (a.username.trim(), b.username.trim());
    if !au.is_empty() && au.eq_ignore_ascii_case(bu) {
        return true;
    }
    let (an, bn) = (a.name.trim(), b.name.trim());
    !an.is_empty() && an.eq_ignore_ascii_case(bn)
}

fn blank(s: &str) -> bool {
    s.trim().is_empty()
}

fn blank_url(url: &Option<String>) -> bool {
    url.as_deref().map(blank).unwrap_or(true)
}

/// Merge provider records into the persisted participant list: de-dup by
/// person (highest role wins, blank name/username/avatar back-filled),
/// distinct robots stay distinct (they carry different ids/usernames, so the
/// person test never merges them), then order `author` → `creator` →
/// `participant` (a stable sort keeps the provider's own order within a role).
pub fn aggregate_participants(inputs: Vec<ParticipantInput>) -> Vec<Participant> {
    let mut merged: Vec<ParticipantInput> = Vec::new();
    for incoming in inputs {
        if blank(&incoming.name) && blank(&incoming.username) {
            continue;
        }
        match merged.iter_mut().find(|existing| is_same_person(existing, &incoming)) {
            Some(existing) => {
                if incoming.role.priority() > existing.role.priority() {
                    existing.role = incoming.role;
                }
                if blank(&existing.name) {
                    existing.name = incoming.name.clone();
                }
                if blank(&existing.username) {
                    existing.username = incoming.username.clone();
                }
                if blank_url(&existing.avatar_url) {
                    existing.avatar_url = incoming.avatar_url.clone();
                }
                existing.id = existing.id.or(incoming.id);
                existing.bot = existing.bot || incoming.bot;
            }
            None => merged.push(incoming),
        }
    }
    merged.sort_by_key(|a| std::cmp::Reverse(a.role.priority()));
    merged
        .into_iter()
        .map(|input| Participant {
            name: if blank(&input.name) {
                input.username.clone()
            } else {
                input.name
            },
            username: input.username,
            avatar_url: input.avatar_url.filter(|u| !blank(u)),
            role: input.role,
            bot: input.bot,
        })
        .collect()
}

/// Merge `incoming` participants into an already-aggregated `base` list,
/// re-running the same de-dup/order rules. Used to fold note/review authors
/// (which arrive after the MR participants fetch) into `SourceMeta`.
pub fn merge_participants(base: &mut Vec<Participant>, incoming: Vec<Participant>) {
    let to_input = |p: Participant| ParticipantInput {
        id: None,
        name: p.name,
        username: p.username,
        avatar_url: p.avatar_url,
        role: p.role,
        bot: p.bot,
    };
    let mut inputs: Vec<ParticipantInput> = base.drain(..).map(to_input).collect();
    inputs.extend(incoming.into_iter().map(to_input));
    *base = aggregate_participants(inputs);
}

// ─── GitLab MR 信息 ─────────────────────────

/// Metadata about a GitLab Merge Request or GitHub Pull Request.
///
/// Carries identifying information, branch details, and optional SHA
/// references used for inline comment positioning.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MRInfo {
    /// Repository path (e.g. `owner/repo` or `group/project`).
    pub project_path: String,
    /// MR/PR numeric ID (iid).
    pub mr_iid: u32,
    /// Title of the merge request or pull request.
    pub title: String,
    /// Description / body text of the MR/PR.
    pub description: String,
    /// Source branch name (feature branch).
    pub source_branch: String,
    /// Target branch name (base branch, e.g. `main`).
    pub target_branch: String,
    /// Git commit SHA of the latest diff.
    pub git_hash: String,
    /// SHA of the target branch HEAD (used for inline comment positions).
    pub base_sha: Option<String>,
    /// SHA of the merge-base (used for inline comment positions).
    pub start_sha: Option<String>,
    /// SHA of the merge commit (GitHub only, after PR is merged).
    pub merge_commit_sha: Option<String>,
    /// Author's username or login (GitHub login / GitLab username).
    pub pr_author: Option<String>,
    /// Author of the MR's head commit (`author_name` from the commit API).
    ///
    /// RENG-27: the History "author" column prefers this over `pr_author` —
    /// the commit author is who actually wrote the code under review, while
    /// `pr_author` is whoever opened the MR (often an admin/bot account).
    /// Best-effort: `None` when the provider cannot resolve it, in which case
    /// callers fall back to `pr_author`. `#[serde(default)]` keeps previously
    /// serialized `MRInfo` JSON (without this field) deserializable.
    #[serde(default)]
    pub commit_author: Option<String>,
    /// Author's platform-specific unique ID (GitHub user.id / GitLab user.id).
    pub pr_author_id: Option<u64>,
    /// RENG-43: everyone involved in the MR/PR, already de-duplicated and
    /// ordered by [`aggregate_participants`] (head-commit author → MR/PR
    /// opener → commenters/reviewers). Empty when the provider resolves
    /// nobody. `#[serde(default)]` keeps previously serialized `MRInfo` JSON
    /// (without this field) deserializable.
    #[serde(default)]
    pub participants: Vec<Participant>,
    /// Rendered MR discussion-history section injected into review prompts
    /// (0.10.0 §7.2). Filled by the pre-review discussion tap (DB-first,
    /// GitLab API fallback); `None` = no context injected (0.9 behaviour).
    /// Runtime-only: never serialized into task records or the DB.
    #[serde(skip, default)]
    pub discussion_context: Option<String>,
    /// Rendered AGENTS.md section injected into review prompts (RENG-18).
    /// Filled by the pre-review agents-md tap; `None` = no context injected.
    /// Runtime-only: never serialized into task records or the DB.
    #[serde(skip, default)]
    pub agents_md: Option<String>,
}

impl MRInfo {
    /// Create a new MRInfo with default values for optional fields.
    pub fn new(project_path: String, title: String, source_branch: String, target_branch: String) -> Self {
        Self {
            project_path,
            mr_iid: 0,
            title,
            description: String::new(),
            source_branch,
            target_branch,
            git_hash: "0000".to_string(),
            base_sha: None,
            start_sha: None,
            merge_commit_sha: None,
            pr_author: None,
            pr_author_id: None,
            commit_author: None,
            participants: Vec::new(),
            discussion_context: None,
            agents_md: None,
        }
    }
}

// ─── Diff 相关 ──────────────────────────────

/// A single file within a parsed diff, including its hunks and change statistics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffFile {
    /// Relative file path (new version).
    pub path: String,
    /// Original file path before the change.
    pub old_path: String,
    /// New file path after the change (may differ for renames).
    pub new_path: String,
    /// Change status (e.g. `added`, `modified`, `deleted`, `renamed`).
    pub status: String,
    /// Number of added lines.
    pub additions: u32,
    /// Number of deleted lines.
    pub deletions: u32,
    /// Contiguous diff hunks within this file.
    pub hunks: Vec<DiffHunk>,
}

/// A contiguous hunk (section) within a file diff, with line-range metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffHunk {
    /// Unified-diff hunk header (e.g. `@@ ... @@`).
    pub header: String,
    /// Starting line number in the old file.
    pub old_start: u32,
    /// Number of lines in the old file for this hunk.
    pub old_lines: u32,
    /// Starting line number in the new file.
    pub new_start: u32,
    /// Number of lines in the new file for this hunk.
    pub new_lines: u32,
    /// Individual lines making up this hunk.
    pub lines: Vec<DiffLine>,
}

/// A single line within a diff hunk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffLine {
    /// Whether the line was added, deleted, or is context.
    pub kind: DiffLineKind,
    /// The raw line content (without leading `+`/`-`/` `).
    pub content: String,
    /// Line number in the old file (None for added lines).
    pub old_line_no: Option<u32>,
    /// Line number in the new file (None for deleted lines).
    pub new_line_no: Option<u32>,
}

/// Classification of a diff line.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DiffLineKind {
    /// Line was added in the new version.
    Add,
    /// Line was removed from the old version.
    Delete,
    /// Unchanged context line shown for reference.
    Context,
}

// ─── Review Input ────────────────────────────

/// The source of a code review request.
///
/// Can originate from a GitLab MR URL, a GitHub PR URL, or a local
/// repository directory with optional branch and commit-range filters.
#[derive(Debug, Clone)]
pub enum ReviewInput {
    /// Review a GitLab merge request by its web URL.
    GitLabMR {
        /// Full URL to the GitLab MR.
        url: String,
    },
    /// Review a GitHub pull request by its web URL.
    GitHubPR {
        /// Full URL to the GitHub PR.
        url: String,
    },
    /// Review a local Git repository, optionally scoped to a branch or commit range.
    LocalRepo {
        /// Path to the local repository directory.
        path: String,
        /// Git ref (branch/commit) to use as the base (e.g. `main`).
        base_ref: Option<String>,
        /// Git ref (branch/commit) to use as the head (e.g. a feature branch).
        head_ref: Option<String>,
        /// If `true`, only review staged changes (like `git diff --cached`).
        staged: bool,
        /// Include commits from this date (ISO 8601) onward.
        since: Option<String>,
        /// Exclude commits after this date (ISO 8601).
        until: Option<String>,
    },
}

impl ReviewInput {
    /// Create a `LocalRepo` input for the given directory (no branch/date filters).
    pub fn local(path: &str) -> Self {
        ReviewInput::LocalRepo {
            path: path.to_string(),
            base_ref: None,
            head_ref: None,
            staged: false,
            since: None,
            until: None,
        }
    }
}

/// Interface for browsing repository files at a given Git ref.
///
/// Implementations exist for GitLab and GitHub to support cross-referencing
/// code outside the diff while reviewing.
pub trait RepoBrowser: Send + Sync {
    /// Read the contents of a file at the given Git ref.
    fn get_file(&self, path: &str, git_ref: &str) -> anyhow::Result<String>;
    /// Search the repository for code matching the given query.
    fn search_code(&self, query: &str) -> anyhow::Result<Vec<String>>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_review_input_local() {
        let input = ReviewInput::local("/tmp/test-repo");
        match input {
            ReviewInput::LocalRepo { path, .. } => assert_eq!(path, "/tmp/test-repo"),
            _ => panic!("Expected LocalRepo variant"),
        }
    }
}

#[cfg(test)]
mod participants_tests {
    use super::*;

    fn input(id: Option<u64>, name: &str, username: &str, role: ParticipantRole) -> ParticipantInput {
        ParticipantInput::new(name, role).with_id(id).with_username(username)
    }

    /// Role serialization is the persisted contract: snake_case strings the
    /// REST layer passes through untouched.
    #[test]
    fn participant_role_serializes_snake_case() {
        assert_eq!(serde_json::to_string(&ParticipantRole::Author).unwrap(), "\"author\"");
        assert_eq!(serde_json::to_string(&ParticipantRole::Creator).unwrap(), "\"creator\"");
        assert_eq!(
            serde_json::to_string(&ParticipantRole::Participant).unwrap(),
            "\"participant\""
        );
    }

    /// Ordering is author → creator → participant regardless of input order.
    #[test]
    fn aggregate_orders_by_role_priority() {
        let out = aggregate_participants(vec![
            input(Some(3), "Carol", "carol", ParticipantRole::Participant),
            input(Some(2), "Bob", "bob", ParticipantRole::Creator),
            input(Some(1), "Alice", "alice", ParticipantRole::Author),
        ]);
        let roles: Vec<ParticipantRole> = out.iter().map(|p| p.role).collect();
        assert_eq!(
            roles,
            vec![
                ParticipantRole::Author,
                ParticipantRole::Creator,
                ParticipantRole::Participant
            ]
        );
        let names: Vec<&str> = out.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, vec!["Alice", "Bob", "Carol"]);
    }

    /// The same person arriving as both creator and author keeps only the
    /// highest-priority entry, with blanks back-filled from the loser.
    #[test]
    fn aggregate_dedups_same_person_keeping_highest_role() {
        let out = aggregate_participants(vec![
            ParticipantInput::new("Alice", ParticipantRole::Author)
                .with_id(Some(1))
                .with_avatar(Some("http://img/alice".into())),
            input(Some(1), "", "alice", ParticipantRole::Creator),
        ]);
        assert_eq!(out.len(), 1, "one person, one entry");
        assert_eq!(out[0].role, ParticipantRole::Author, "author wins");
        assert_eq!(out[0].name, "Alice");
        assert_eq!(out[0].username, "alice", "blank username back-filled");
        assert_eq!(out[0].avatar_url.as_deref(), Some("http://img/alice"));
    }

    /// Username de-dups when no ids are available; display name is the last
    /// resort. Case-insensitive on both.
    #[test]
    fn aggregate_dedups_by_username_then_name() {
        let out = aggregate_participants(vec![
            input(None, "Alice A", "alice", ParticipantRole::Participant),
            input(None, "Alice A", "ALICE", ParticipantRole::Creator),
            input(None, "Bob B", "", ParticipantRole::Participant),
            input(None, "bob b", "", ParticipantRole::Participant),
        ]);
        assert_eq!(out.len(), 2, "alice and bob only");
        assert_eq!(out[0].role, ParticipantRole::Creator, "alice upgraded by username");
        assert_eq!(out[1].name, "Bob B");
    }

    /// Distinct robots are distinct subjects: never merged, and `_bot`
    /// usernames (or an explicit bot flag) carry the bot marker through.
    #[test]
    fn aggregate_keeps_distinct_bots_and_flags_them() {
        let out = aggregate_participants(vec![
            ParticipantInput::new("Group Bot", ParticipantRole::Participant).with_username("group_1_bot"),
            ParticipantInput::new("Other Bot", ParticipantRole::Participant).with_username("other_2_bot"),
            ParticipantInput::new("Reviewer", ParticipantRole::Participant)
                .with_username("reviewer")
                .with_bot(true),
            ParticipantInput::new("Human", ParticipantRole::Creator).with_username("human"),
        ]);
        assert_eq!(out.len(), 4, "four distinct subjects");
        let bots: Vec<bool> = out.iter().map(|p| p.bot).collect();
        assert!(bots.iter().filter(|b| **b).count() == 3, "three bots: {bots:?}");
        let human = out.iter().find(|p| p.username == "human").unwrap();
        assert!(!human.bot, "plain handles are not bots");
    }

    /// People without an avatar keep `avatar_url: None` (no fabricated URL),
    /// and a missing display name falls back to the username.
    #[test]
    fn aggregate_handles_missing_avatar_and_missing_name() {
        let out = aggregate_participants(vec![input(Some(5), "", "ghost", ParticipantRole::Participant)]);
        assert_eq!(out[0].name, "ghost", "name falls back to username");
        assert!(out[0].avatar_url.is_none());
    }

    /// No provider participants at all is a valid, empty result.
    #[test]
    fn aggregate_empty_input_yields_empty() {
        assert!(aggregate_participants(Vec::new()).is_empty());
    }

    /// `merge_participants` re-runs the same rules across sources.
    #[test]
    fn merge_participants_folds_extra_people_into_existing_list() {
        let mut base = aggregate_participants(vec![
            input(Some(1), "Alice", "alice", ParticipantRole::Author),
            input(Some(2), "Bob", "bob", ParticipantRole::Creator),
        ]);
        // A note author already known is not duplicated; a new one is appended.
        merge_participants(
            &mut base,
            vec![
                Participant {
                    name: "Bob".into(),
                    username: "bob".into(),
                    avatar_url: Some("http://img/bob".into()),
                    role: ParticipantRole::Participant,
                    bot: false,
                },
                Participant {
                    name: "Carol".into(),
                    username: "carol".into(),
                    avatar_url: None,
                    role: ParticipantRole::Participant,
                    bot: false,
                },
            ],
        );
        assert_eq!(base.len(), 3);
        let bob = base.iter().find(|p| p.username == "bob").unwrap();
        assert_eq!(bob.role, ParticipantRole::Creator, "higher role survives the merge");
        assert_eq!(bob.avatar_url.as_deref(), Some("http://img/bob"), "avatar back-filled");
        assert_eq!(base.last().unwrap().name, "Carol", "participants stay last");
    }
}
