//! Core data models shared throughout the review engine.
//!
//! Re-exports types from three private submodules: `config` (application
//! configuration structures including [`AppConfig`], [`LLMConfig`],
//! [`ScoringConfig`]), `expert` (expert definitions, triggers, and
//! report types like [`ExpertReport`], [`AggregatedReport`],
//! [`GlobalReviewContext`]), and `finding` (review findings with
//! severity, confidence, line numbers, and recommendations). Also
//! defines top-level enums and structs such as [`RiskLevel`],
//! [`OverallAssessment`], [`Severity`], and [`ReviewInput`].

mod config;
mod expert;
mod finding;

pub use config::*;
pub use expert::*;
pub use finding::*;

use serde::{Deserialize, Serialize};

// ─── Risk Level & Overall Assessment ───────────

/// Overall risk level for a review.
#[derive(Debug, Clone, PartialEq, PartialOrd, Serialize, Deserialize, Default)]
pub enum RiskLevel {
    Low,
    LowMedium,
    #[default]
    Medium,
    High,
    Critical,
}

impl std::fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RiskLevel::Low => write!(f, "low"),
            RiskLevel::LowMedium => write!(f, "low-medium"),
            RiskLevel::Medium => write!(f, "medium"),
            RiskLevel::High => write!(f, "high"),
            RiskLevel::Critical => write!(f, "critical"),
        }
    }
}

/// Overall assessment of a review, computed from expert scores.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OverallAssessment {
    /// Computed score (0-100).
    pub score: u8,
    /// Risk level derived from the score.
    pub risk_level: RiskLevel,
    /// Lead reviewer's override assessment (optional).
    pub lead_override: Option<String>,
    /// Summary of key findings.
    pub tl_dr: String,
}

// ─── Global Review Context ────────────────────

/// High-level context for a PR review, generated by the lead reviewer expert.
///
/// Contains a summary, identified risk areas, files that need focused
/// attention, and tailored guidance for domain-specific experts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlobalReviewContext {
    /// One-paragraph summary of the PR's purpose and scope.
    pub summary: String,
    /// List of risk areas identified (e.g. "Security: auth middleware changes").
    pub risk_areas: Vec<String>,
    /// Files that expert reviewers should prioritise.
    pub focus_files: Vec<String>,
    /// Tailored guidance for domain experts.
    pub guidance: String,
}

impl GlobalReviewContext {
    /// Format the context as a Markdown section for inclusion in LLM prompts.
    pub fn to_prompt_section(&self) -> String {
        format!(
            "## Global Review Context (PR Overview)\n\n\
             Summary: {}\n\n\
             Risk Areas: {}\n\n\
             Focus Files: {}\n\n\
             Expert Guidance: {}",
            self.summary,
            self.risk_areas.join(", "),
            self.focus_files.join(", "),
            self.guidance,
        )
    }
}

// ─── GitLab MR 信息 ─────────────────────────

/// Metadata about a GitLab Merge Request or GitHub Pull Request.
///
/// Carries identifying information, branch details, and optional SHA
/// references used for inline comment positioning.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MRInfo {
    /// Repository path (e.g. `owner/repo` or `group/project`).
    pub project_path: String,
    /// MR/PR numeric ID (iid).
    pub mr_iid: u32,
    /// Title of the merge request or pull request.
    pub title: String,
    /// Description / body text of the MR/PR.
    pub description: String,
    /// Source branch name (feature branch).
    pub source_branch: String,
    /// Target branch name (base branch, e.g. `main`).
    pub target_branch: String,
    /// Git commit SHA of the latest diff.
    pub git_hash: String,
    /// SHA of the target branch HEAD (used for inline comment positions).
    pub base_sha: Option<String>,
    /// SHA of the merge-base (used for inline comment positions).
    pub start_sha: Option<String>,
    /// SHA of the merge commit (GitHub only, after PR is merged).
    pub merge_commit_sha: Option<String>,
    /// Author's username or login (GitHub login / GitLab username).
    pub pr_author: Option<String>,
    /// Author's platform-specific unique ID (GitHub user.id / GitLab user.id).
    pub pr_author_id: Option<u64>,
}

impl MRInfo {
    /// Create a new MRInfo with default values for optional fields.
    pub fn new(project_path: String, title: String, source_branch: String, target_branch: String) -> Self {
        Self {
            project_path,
            mr_iid: 0,
            title,
            description: String::new(),
            source_branch,
            target_branch,
            git_hash: "0000".to_string(),
            base_sha: None,
            start_sha: None,
            merge_commit_sha: None,
            pr_author: None,
            pr_author_id: None,
        }
    }
}

// ─── Diff 相关 ──────────────────────────────

/// A single file within a parsed diff, including its hunks and change statistics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffFile {
    /// Relative file path (new version).
    pub path: String,
    /// Original file path before the change.
    pub old_path: String,
    /// New file path after the change (may differ for renames).
    pub new_path: String,
    /// Change status (e.g. `added`, `modified`, `deleted`, `renamed`).
    pub status: String,
    /// Number of added lines.
    pub additions: u32,
    /// Number of deleted lines.
    pub deletions: u32,
    /// Contiguous diff hunks within this file.
    pub hunks: Vec<DiffHunk>,
}

/// A contiguous hunk (section) within a file diff, with line-range metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffHunk {
    /// Unified-diff hunk header (e.g. `@@ ... @@`).
    pub header: String,
    /// Starting line number in the old file.
    pub old_start: u32,
    /// Number of lines in the old file for this hunk.
    pub old_lines: u32,
    /// Starting line number in the new file.
    pub new_start: u32,
    /// Number of lines in the new file for this hunk.
    pub new_lines: u32,
    /// Individual lines making up this hunk.
    pub lines: Vec<DiffLine>,
}

/// A single line within a diff hunk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffLine {
    /// Whether the line was added, deleted, or is context.
    pub kind: DiffLineKind,
    /// The raw line content (without leading `+`/`-`/` `).
    pub content: String,
    /// Line number in the old file (None for added lines).
    pub old_line_no: Option<u32>,
    /// Line number in the new file (None for deleted lines).
    pub new_line_no: Option<u32>,
}

/// Classification of a diff line.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DiffLineKind {
    /// Line was added in the new version.
    Add,
    /// Line was removed from the old version.
    Delete,
    /// Unchanged context line shown for reference.
    Context,
}

// ─── Review Input ────────────────────────────

/// The source of a code review request.
///
/// Can originate from a GitLab MR URL, a GitHub PR URL, or a local
/// repository directory with optional branch and commit-range filters.
#[derive(Debug, Clone)]
pub enum ReviewInput {
    /// Review a GitLab merge request by its web URL.
    GitLabMR {
        /// Full URL to the GitLab MR.
        url: String,
    },
    /// Review a GitHub pull request by its web URL.
    GitHubPR {
        /// Full URL to the GitHub PR.
        url: String,
    },
    /// Review a local Git repository, optionally scoped to a branch or commit range.
    LocalRepo {
        /// Path to the local repository directory.
        path: String,
        /// Git ref (branch/commit) to use as the base (e.g. `main`).
        base_ref: Option<String>,
        /// Git ref (branch/commit) to use as the head (e.g. a feature branch).
        head_ref: Option<String>,
        /// If `true`, only review staged changes (like `git diff --cached`).
        staged: bool,
        /// Include commits from this date (ISO 8601) onward.
        since: Option<String>,
        /// Exclude commits after this date (ISO 8601).
        until: Option<String>,
    },
}

impl ReviewInput {
    /// Create a `LocalRepo` input for the given directory (no branch/date filters).
    pub fn local(path: &str) -> Self {
        ReviewInput::LocalRepo {
            path: path.to_string(),
            base_ref: None,
            head_ref: None,
            staged: false,
            since: None,
            until: None,
        }
    }
}

/// Interface for browsing repository files at a given Git ref.
///
/// Implementations exist for GitLab and GitHub to support cross-referencing
/// code outside the diff while reviewing.
pub trait RepoBrowser: Send + Sync {
    /// Read the contents of a file at the given Git ref.
    fn get_file(&self, path: &str, git_ref: &str) -> anyhow::Result<String>;
    /// Search the repository for code matching the given query.
    fn search_code(&self, query: &str) -> anyhow::Result<Vec<String>>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_review_input_local() {
        let input = ReviewInput::local("/tmp/test-repo");
        match input {
            ReviewInput::LocalRepo { path, .. } => assert_eq!(path, "/tmp/test-repo"),
            _ => panic!("Expected LocalRepo variant"),
        }
    }
}
